### ISSUE TITLE
Login hangs in Firefox due to fingerprint protection - Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).

### ISSUE THREAD

**Issue by StoppingBuck** [etesync/etesync-notes#166]
Hey. Trying to login to https://notes.etesync.com in my Firefox seems to hang on the progress bar "Loading Please wait..." which never completes.

Going to inspect the JavaScript console shows that moz-extension://4e7776d4-e538-4a1a-b857-3c5080fe4a2b/data/fingerprint-protection.js gives off the error "Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”)."

Everything works fine in Chrome, so I'm guessing this is an issue related to the fingerprint protection in Firefox.

![image](https://user-images.githubusercontent.com/8426548/109386751-29e71080-78fd-11eb-82a9-5c3e8072a58e.png)

**Comment by StoppingBuck** [comment]
Wait, I just realized that it actually logged me in that time lol. Maybe it was just a temporary hiccup? I'm keeping this open since the error still seems like an error, but maybe it doesn't always completely hang login...

**Comment by zecakeh** [comment]
This issue seems like a duplicate of #131.

The error, doesn't prevent the website from working. From the looks of it it's more that the security settings of the website prevents some Firefox extensions from working correctly (we've seen this with Privace Badger in #131). This is a known issue in Firefox actually so we can't do much.

**Comment by StoppingBuck** [comment]
@zecakeh Good catch, closing this as a duplicate of #131 :slightly_smiling_face:
