### ISSUE TITLE
Feature request: Monospaced font

### ISSUE THREAD

**Issue by Brog33** [etesync/etesync-notes#54]
Would be very nice to have the option to use a monospaced font.

**Comment by Eryc-M** [comment]
I second this feature request. A Monospaced font in the editor view would help greatly, especially with tables. If possible, would like to have to option for a monospaced font in the editor view and rendered view.

**Comment by zecakeh** [comment]
I'd like to work on that in the next days and it should be trivial. As long as we're into it, should we provide other choices than the default font and a monospace font?

**Comment by tasn** [comment]
@zecakeh , Is it possible to only offer the fonts available in the system? So that users can just choose any of the fonts they have installed? We could potentially ship our own fonts, but I'm much rather not. I'm pretty sure it's possible to choose system fonts, so it's just about listing them or having our own preset list.

**Comment by zecakeh** [comment]
I'm working on it but I'm sticking with three choices right now that are available on all platforms: sans-serif (default system font), monospace and serif.
I believe showing all fonts would complicate things especially for iOS users that have at least as many fonts as on any computer. Android is way more limited.

**Comment by tasn** [comment]
@zecakeh, I think you are right. Good idea, go ahead with that!

**Comment by tasn** [comment]
Fixed in 0149a259df30358a4e6291f0e163afa3760d3005
