### ISSUE TITLE
Add support for sharing notebooks

### ISSUE THREAD

**Issue by mrichtsfeld** [etesync/etesync-notes#57]
It would be great if it is possible to share notebooks which brings the app closer to be a real alternative to Evernotes. 

I'm a developer and happy to contribute. 

Thanks

**Comment by tasn** [comment]
Sharing is already supported, though I agree it should probably be more discoverable.
What you need to do:
1. Open the side menu
2. Click on a collection name
3. Top right menu -> Manage notebook
4. Members
5. Invite (top right icon)

Btw, the app is built in react-native so if you know TypeScript/JavaScript and are willing to help, there's a lot that could be done. Let us know!

I'm closing this ticket as it's already solved.

**Comment by mrichtsfeld** [comment]
Thank you for pointing that out. It is indeed well hidden :). 

Yes, I'm willing to help. What is the best way to get in touch? I would love to see a roadmap to see where I can contribute best. I have written apps in React previously and a lot of Node and Angular as well.

**Comment by tasn** [comment]
Thanks! That would be amazing!

Ways to contact:
Email: tom @ the domain of the website
Chat (IRC/Matrix/Web): https://www.etesync.com/community-chat/

You can also take a look at the tickets for what people are asking for, though I think it's better to chat rather than do that, as I can probably point you to the more important and yet easy things to implement.

Thanks a lot!
